import type { Metadata } from "next";
import { Footer } from "@/frontend/components/ui/footer/Footer";
import { Header } from "@/frontend/components/ui/header/Header";

export const metadata: Metadata = {
  title: "Meal-Share UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
      <Header />
        <main >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
