import type { Metadata } from "next";
import { Footer } from "@/frontend/components/ui/footer/Footer";


export const metadata: Metadata = {
  title: "week-4-react-2-classwork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
        <main >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
